### PR TITLE
Addition of a few more programming languages?

### PR DESCRIPTION
**Pull request by ethindp**
I have added the Silver, Oxygene, and Iodine programming languages. Silver is a programming language based on Swift for the .NET platform. Oxygene is a fork of Pascal to be better than Pascal, and Iodine is a fork of the Java programming language, which will soon be available on the .NET platform. The Iodine language will not compile yet because there is no publicly released compiler for it, but if you get the RemObjects Elements compiler (found at http://www.elementscompiler.com) you can compile the other two.

### CODE REVIEW

**Comment by dkager** [comment]
Manually merged. Thanks!

**Comment by ethindp** [comment]
NP. I'll try and port it to F# next, although I'm not very proficient
in F#. I'll try it, though!

On 1/27/17, Davy Kager <notifications@github.com> wrote:
> Manually merged. Thanks!
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dkager/tolk/pull/7#issuecomment-275675375


-- 
Signed,
Ethin D. Probst

**Comment by dkager** [comment]
By the way, did you intentionally leave calls to `Console.WriteLine` in all three examples?

**Comment by ethindp** [comment]
Yes. They all reference the .NET framework. We'll need to create an
elements project file and we'll need to ensure that users know that
they will require Microsoft Visual Studio with RemObjects Elements
(http://www.elementscompiler.com) in order to build all three of them,
as none of them are supported natively by Visual Studio. I'll outline
them here:
Oxygene is a language that enhances the Pascal programming language
created by Niklaus Wirth in 1970 and with major implementations
including CDC 6000, Embarcadero Delphi, ICL 1900, Pascal-P, PDP-11,
PDP-10, IBM System/370, HP Pascal, Free Pascal, and GNU Pascal, with
FreePascal being the most popular. It also has many dialects,
including Delphi, Turbo Pascal, and UCSD Pascal. It is primarily meant
for educational purposes and, as far as I know, not used by very many
people out there for heavy-duty tasks such as game programming or
IDEs. Oxygene is an extension by adding several new features,
including namespaces and the ability to create a "shared project", a
project that allows you to write code in Oxygene, C# and Swift. It
also can compile to native code like normal Pascal can and to the .NET
platform, the JVM and to Mac OS X.
RemObjects C# is your standard implementation of C#. The only
Additional features are shared projects and the ability to write Java,
.NET, Mac OS X and Native C# Apps.
Finally, Swift-Silver is Silver, a standard implementation of Swift, a
new programming language created by Apple for the aid of helping
people write Mac OS X apps. Swift is now available on Linux, too.
Silver adds several things to Swift, including annotations and the
ability to use .NET, Java, Mac OS X and native system libraries.
So, there you go.

On 1/28/17, Davy Kager <notifications@github.com> wrote:
> By the way, did you intentionally leave calls to `Console.WriteLine` in all
> three examples?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dkager/tolk/pull/7#issuecomment-275839830


-- 
Signed,
Ethin D. Probst

**Comment by dkager** [comment]
> We'll need to create an elements project file and we'll need to ensure that users know that they will require Microsoft Visual Studio with RemObjects Elements ...

This is getting out of scope. It's good to have it documented in this PR, but all we need to do is provide wrappers for people to use in an environment they already know. As such, the work is now complete for as far as Tolk is concerned. Thanks again for the additions!

**Comment by ethindp** [comment]
No problem! I'll keep adding more, if you'd like?

On 1/28/17, Davy Kager <notifications@github.com> wrote:
>> We'll need to create an elements project file and we'll need to ensure
>> that users know that they will require Microsoft Visual Studio with
>> RemObjects Elements ...
>
> This is getting out of scope. It's good to have it documented in this PR,
> but all we need to do is provide wrappers for people to use in an
> environment they already know. As such, the work is now complete for as far
> as Tolk is concerned. Thanks again for the additions!
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dkager/tolk/pull/7#issuecomment-275861984


-- 
Signed,
Ethin D. Probst

**Comment by dkager** [comment]
I can add them to the contrib folder, but keep in mind it is not the core of this project. :)

**Pull request closed without merging**
